# Generated by Django 5.0.6 on 2024-05-24 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title', models.CharField(max_length=40)),
                ('banner_list_date', models.CharField(choices=[('January', 'January_banners'), ('February', 'February_banners'), ('March', 'March_banners'), ('May', 'May_banners'), ('June', 'June_banners'), ('July', 'July_banners'), ('August', 'August_banners'), ('September', 'September_banners'), ('November', 'November_banners'), ('December', 'December_banners')], default='Test_period', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='BannerImgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_img', models.ImageField(default='product_default.jpg', upload_to='product_pics')),
                ('banner_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='allsellapp.homebanner')),
            ],
        ),
    ]
