# Generated by Django 4.0.2 on 2022-03-04 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allsellapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration_model',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
