# Generated by Django 4.0.3 on 2022-03-14 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allsellapp', '0002_product_model_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_model',
            name='img',
        ),
        migrations.AlterField(
            model_name='product_model',
            name='prod_img',
            field=models.ImageField(default='product_default.jpg', upload_to='product_pics'),
        ),
    ]
