# Generated by Django 4.0.3 on 2022-03-14 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allsellapp', '0003_remove_product_model_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_model',
            name='prod_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
