# Generated by Django 4.0.3 on 2022-04-24 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allsellapp', '0006_alter_product_model_prod_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_model',
        ),
    ]
