# Generated by Django 4.0.3 on 2022-05-17 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('allsellapp', '0007_delete_product_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title', models.CharField(max_length=40)),
                ('banner_list_date', models.CharField(choices=[('January', 'January_banners'), ('February', 'February_banners'), ('March', 'March_banners'), ('May', 'May_banners'), ('June', 'June_banners'), ('July', 'July_banners'), ('August', 'August_banners'), ('September', 'September_banners'), ('November', 'November_banners'), ('December', 'December_banners')], default='Test_period', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Banner_imgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_img', models.ImageField(default='product_default.jpg', upload_to='product_pics')),
                ('banner_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='allsellapp.home_banner')),
            ],
        ),
    ]
