# Generated by Django 4.0.3 on 2022-05-17 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allsellapp', '0008_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Banner_imgs',
            new_name='BannerImgs',
        ),
        migrations.RenameModel(
            old_name='Home_banner',
            new_name='HomeBanner',
        ),
    ]
