# Generated by Django 4.0.3 on 2022-04-24 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(max_length=40)),
                ('prod_desc', models.CharField(max_length=100)),
                ('currency', models.CharField(choices=[('$', 'US Dollars ($)')], default='$', max_length=5)),
                ('prod_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('prod_img', models.ImageField(default='product_default.jpg', upload_to='product_pics')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
