# Generated by Django 5.0.6 on 2024-05-23 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_productmodel_product_discount_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='product_discount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
