# Generated by Django 4.0.3 on 2022-04-27 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_model_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_imgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_img', models.ImageField(default='product_default.jpg', upload_to='product_pics')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product_model')),
            ],
        ),
    ]
