# Generated by Django 4.0.3 on 2022-04-27 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_imgs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_imgs',
            new_name='Product_img',
        ),
        migrations.CreateModel(
            name='Product_img_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product_model')),
            ],
        ),
    ]
