# Generated by Django 4.0.3 on 2022-04-27 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_product_imgs_product_img_product_img_item'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_img',
            new_name='Product_imgs',
        ),
        migrations.DeleteModel(
            name='Product_img_item',
        ),
    ]
