# Generated by Django 5.0.6 on 2024-05-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_orderproduct_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='default',
        ),
        migrations.AddField(
            model_name='address',
            name='user_first_name',
            field=models.CharField(default='First name', max_length=100),
        ),
        migrations.AddField(
            model_name='address',
            name='user_last_name',
            field=models.CharField(default='Last name', max_length=100),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line_1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='address_line_2',
            field=models.CharField(max_length=200),
        ),
    ]
