# Generated by Django 5.0.6 on 2024-05-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_customers_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='currency',
        ),
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(choices=[('$', 'US Dollars ($)')], default='$', max_length=5),
        ),
    ]
