# Generated by Django 4.0.3 on 2022-04-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_rename_product_img_product_imgs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_imgs',
            name='prod_img_title',
            field=models.CharField(default='prod_title', max_length=40),
            preserve_default=False,
        ),
    ]
