# Generated by Django 5.0.6 on 2024-05-23 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_productmodel_currency_order_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='currency',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='currency',
            field=models.CharField(choices=[('$', 'US Dollars ($)')], default='$', max_length=5),
        ),
    ]
