# Generated by Django 5.0.6 on 2024-05-27 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_address_default_address_user_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
    ]
