# Generated by Django 5.0.6 on 2024-05-28 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_customer_email_remove_customer_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ordered',
            new_name='completed',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='ordered_date',
            new_name='completed_date',
        ),
    ]
