# Generated by Django 4.0.3 on 2022-04-29 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_model_img_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Clothes & Accesories', 'clothes and accesories'), ('Computers, Tablets and IT Accessories', 'PC, Tablets and stuff'), ('Toys & Games', 'Toys and Games'), ('Bikes and Automobiles', 'Cars and bikes')], default='Category_test', max_length=225)),
                ('color_tag', models.CharField(choices=[('pink-paradise', 'pink'), ('dark-pastel-green', 'pastel green'), ('navy-blue', 'Navy blue'), ('jasmine', 'Jasmine')], default='color_test', max_length=225)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='product_model',
            name='categories',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Category', to='products.product_category'),
        ),
    ]
