# Generated by Django 4.0.3 on 2022-04-30 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_model_categories'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_imgs',
            new_name='Product_img',
        ),
        migrations.AlterField(
            model_name='product_category',
            name='category',
            field=models.CharField(choices=[('Clothes & Accesories', 'clothes and accesories'), ('Electronics', 'electronics'), ('Toys & Games', 'Toys and Games'), ('Bikes and Automobiles', 'Cars and bikes')], default='Category_test', max_length=225),
        ),
        migrations.AlterField(
            model_name='product_model',
            name='prod_desc',
            field=models.TextField(max_length=500),
        ),
    ]
