# Generated by Django 4.0.3 on 2022-04-30 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_rename_product_imgs_product_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='img_album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ManyToManyField(to='products.product_img')),
            ],
        ),
    ]
