# Generated by Django 4.0.3 on 2022-04-30 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_img_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='img_album',
            name='album_img_title',
            field=models.CharField(default='test_img_title', max_length=40),
            preserve_default=False,
        ),
    ]
