# Generated by Django 4.0.3 on 2022-05-04 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_img_album_album_img_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_img',
            name='item',
        ),
        migrations.RemoveField(
            model_name='product_model',
            name='prod_img',
        ),
        migrations.AddField(
            model_name='product_model',
            name='prod_imgs',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imgs', to='products.product_img'),
        ),
        migrations.DeleteModel(
            name='img_album',
        ),
    ]
