# Generated by Django 4.0.3 on 2022-05-08 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_remove_product_img_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_model',
            name='prod_imgs',
        ),
        migrations.AddField(
            model_name='product_img',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product_model'),
        ),
        migrations.AddField(
            model_name='product_model',
            name='prod_img',
            field=models.ImageField(default='product_default.jpg', upload_to='product_pics'),
        ),
    ]
