# Generated by Django 4.0.3 on 2022-05-11 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_remove_product_model_prod_imgs_product_img_item_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Banner_imgs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_img', models.ImageField(default='product_default.jpg', upload_to='product_pics')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product_model')),
            ],
        ),
    ]
