# Generated by Django 4.0.3 on 2022-05-11 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_home_banner_banner_imgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_banner',
            name='banner_list_date',
            field=models.CharField(choices=[('January', 'January_banners'), ('February', 'February_banners'), ('March', 'March_banners'), ('May', 'May_banners'), ('June', 'June_banners'), ('July', 'July_banners'), ('August', 'August_banners'), ('September', 'September_banners'), ('November', 'November_banners'), ('December', 'July_banners')], default='Test_period', max_length=30),
        ),
    ]
