# Generated by Django 4.0.3 on 2022-05-16 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0020_remove_product_model_img_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_model',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
