# Generated by Django 4.0.3 on 2022-05-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_alter_product_model_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_model',
            name='prod_discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
