# Generated by Django 4.0.3 on 2022-05-17 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_product_model_prod_discount_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner_imgs',
        ),
        migrations.DeleteModel(
            name='Home_banner',
        ),
    ]
